### ISSUE TITLE
Filter by format or search term

### ISSUE THREAD

**Issue by riceissa** [vipulnaik/contractwork#9]
e.g. a way to search for all timelines payments

**Comment by riceissa** [comment]
Filtering by format has been possible for a while https://contractwork.vipulnaik.com/format.php?format=Timeline

**Comment by vipulnaik** [comment]
You can search by title of the receptacle.

Include partial matches: https://contractwork.vipulnaik.com/tasks.php?receptacle=Timeline+of+malaria

Only exact matches: https://contractwork.vipulnaik.com/tasks.php?receptacle=Timeline+of+malaria&matching=exact

It's also possible for url, just use `receptacle_url` instead of `receptacle`. Remember to URL-encode.
